# Generated by Django 4.0.3 on 2022-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='test', unique=True),
            preserve_default=False,
        ),
    ]
